version: 3
    services:
        webapp:
            image: jesusthehun/featchain-webapp
            build: webapp

        blockchain:
            image: jesusthehun/featchain-blockchain
            build: blockchain
